/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pk.codeapp.methods.Methods;

/**
 *
 * @author Daniel Amador
 */
public class GameMasterInterface extends javax.swing.JFrame
{
    private Methods methods;
    private JFrame afterWindows;
    /**
     * Creates new form GameMasterInterface
     */
    public GameMasterInterface()
    {
        initComponents();
    }
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pk/codeapp/tools/treasurehunter.png"));
        return retValue;
    }
    public void openWindows(JFrame afterWindows, Methods methods)
    {
        this.methods = methods;
        this.setVisible(true);
        this.afterWindows=afterWindows;
        afterWindows.setVisible(false);
        this.setLocationRelativeTo(afterWindows);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Users = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFunction = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        btnAddFunction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Master");
        setIconImage(getIconImage());
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 694));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        jScrollPane1.setViewportView(Users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 270, 480));

        jButton1.setText("Start");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 520, -1, -1));

        jButton2.setText("<<");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, -1, -1));

        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, -1, -1));

        jButton4.setText("End");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Color:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create function");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        txtFunction.setBackground(new java.awt.Color(0, 0, 0));
        txtFunction.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFunction.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Function:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cmbColor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbColor.setForeground(new java.awt.Color(255, 255, 255));
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "blue", "red", "green", "yellow", "orange", "pink", "magenta", "cyan" }));
        getContentPane().add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 250, 40));

        btnAddFunction.setBackground(new java.awt.Color(0, 0, 0));
        btnAddFunction.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFunction.setText("Add Function");
        btnAddFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFunctionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        afterWindows.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAddFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFunctionActionPerformed
        addFunction();
    }//GEN-LAST:event_btnAddFunctionActionPerformed
    private void addFunction(){
        String colorFunction = (String)cmbColor.getSelectedItem();
        if(txtFunction.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Do not leave blanks !!! ");
        }else{
            String name = txtFunction.getText();
            if(methods.addFunction(name, colorFunction))
                 JOptionPane.showMessageDialog(rootPane, "Be added successfully ");
            else{
                 JOptionPane.showMessageDialog(rootPane, "Error !!! ");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMasterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMasterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMasterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMasterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GameMasterInterface().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Users;
    private javax.swing.JButton btnAddFunction;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFunction;
    // End of variables declaration//GEN-END:variables
}
