/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pk.codeapp.methods.Methods;
import static pk.codeapp.screen.MainApp.methods;

/**
 *
 * @author Daniel Amador
 */
public class UserInterface extends javax.swing.JFrame
{

    Methods methods;
    JFrame afterWindows;

    /**
     * Creates new form UserInterface
     */
    public UserInterface()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent evt)
            {

                methods.writeUser();
                methods.writeInTextFile(methods.getTokenFile(), methods.getTokens());
                System.exit(0);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListGames = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAhead = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnPlay = new javax.swing.JToggleButton();
        btnCreateWorld = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jListGames);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 390, 290));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnBack.setForeground(java.awt.Color.white);
        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 50, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Play");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 83, -1));

        btnAhead.setBackground(new java.awt.Color(0, 0, 0));
        btnAhead.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnAhead.setForeground(java.awt.Color.white);
        btnAhead.setText(">>");
        btnAhead.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAheadActionPerformed(evt);
            }
        });
        getContentPane().add(btnAhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 560, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/User.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 250));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Editar Perfil");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, 30));

        lblUsername.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblName.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nombre:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lblEmail.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        btnPlay.setBackground(new java.awt.Color(0, 0, 0));
        btnPlay.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 250, 60));

        btnCreateWorld.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateWorld.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btnCreateWorld.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateWorld.setText("Create Board");
        btnCreateWorld.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCreateWorldMouseClicked(evt);
            }
        });
        btnCreateWorld.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCreateWorldActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateWorld, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 250, 60));

        btnEnd.setBackground(new java.awt.Color(0, 0, 0));
        btnEnd.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnEnd.setForeground(java.awt.Color.white);
        btnEnd.setText("End");
        btnEnd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEndActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 560, 80, -1));

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        btnStart.setForeground(java.awt.Color.white);
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 80, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/map#1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
            // TODO add your handling code here:
        System.out.println(jListGames.getModel());
        if(jListGames.getModel().getSize()!=0){
                methods.setMapSelected(methods.getShowActual().getGameSig());
              play();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Select one map!!","Alert",JOptionPane.WARNING_MESSAGE);
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EditUser editUser = new EditUser();
        editUser.openWindowsFromUser(this);
        editUser.openWindows(this, methods, methods.getActualUser());


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCreateWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWorldActionPerformed
        this.setVisible(false);
        ControlCreateTable aux = new ControlCreateTable();
        aux.beforeWindows(this);
        ControlCreateTable.main(new String[0]);
    }//GEN-LAST:event_btnCreateWorldActionPerformed

    private void btnCreateWorldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateWorldMouseClicked

    }//GEN-LAST:event_btnCreateWorldMouseClicked

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlayActionPerformed
    {//GEN-HEADEREND:event_btnPlayActionPerformed
        // TODO add your handling code here:
         methods.setMapSelected(methods.getActualUser().getGameSig());
        play();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        // TODO add your handling code here:
        jListGames.setModel(methods.printUser(3));
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAheadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAheadActionPerformed
    {//GEN-HEADEREND:event_btnAheadActionPerformed
        // TODO add your handling code here:
        jListGames.setModel(methods.printUser(4));
    }//GEN-LAST:event_btnAheadActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartActionPerformed
    {//GEN-HEADEREND:event_btnStartActionPerformed
        // TODO add your handling code here:
        jListGames.setModel(methods.printUser(1));
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEndActionPerformed
    {//GEN-HEADEREND:event_btnEndActionPerformed
        // TODO add your handling code here:
        jListGames.setModel(methods.printUser(2));
    }//GEN-LAST:event_btnEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UserInterface().setVisible(true);

            }
        });
    }

    public void goBack()
    {
        afterWindows.setVisible(true);
        dispose();
    }

    public void openWindows(JFrame afterWindows, Methods methods)
    {
        this.methods = methods;
        this.setVisible(true);
        this.afterWindows = afterWindows;
        afterWindows.setVisible(false);
        this.setLocationRelativeTo(afterWindows);

        chargeData();

    }

    public void chargeData()
    {
        this.lblEmail.setText("Email: " + methods.getActualUser().getEmail());
        this.lblUsername.setText("Username: " + methods.getActualUser().getUserName());
        this.lblName.setText("Name: " + methods.getActualUser().getName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAhead;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateWorld;
    private javax.swing.JButton btnEnd;
    private javax.swing.JToggleButton btnPlay;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListGames;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
public void play()
    {
        SelectToken select = new SelectToken();
        select.openWindow(this);
    }
}
