/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import pk.codeapp.methods.Methods;
import pk.codeapp.model.Function;

/**
 *
 * @author Jose Pablo Brenes
 */
public class windowsAuxConsult extends javax.swing.JFrame {

    /**
     * Creates new form windowsAuxConsult
     */
    DefaultComboBoxModel<String> cmbModel= new DefaultComboBoxModel();
    private String nameFuction;
    private String color;
    private Function aux;
    private JFrame afterWindows;
    private boolean printSpecialFunction=true;
    public windowsAuxConsult() {
        System.out.println("Entro al constructor");
        
        initComponents();
        loadFunctions(); // Load All fuctions before to start windows
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbFunctions = new javax.swing.JComboBox<>();
        btnAddFunction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the fuction:");

        cmbFunctions.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbFunctions.setForeground(new java.awt.Color(255, 255, 255));

        btnAddFunction.setBackground(new java.awt.Color(0, 0, 0));
        btnAddFunction.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddFunction.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFunction.setText("Add Function");
        btnAddFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFunctionActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addComponent(btnAddFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFunctionActionPerformed
        nameFuction = (String) cmbFunctions.getSelectedItem(); // Get item to combobox selected
        String color = getColorFuctions(nameFuction);
        this.nameFuction = nameFuction;
        checkNameFunction(); // For special Function
        this.color = color;
        System.out.println("El color es: "+color);
        Color colorFrame = getColor(color);
        MainApp.methods.setColor(colorFrame);
        MainApp.methods.setActivePaint(true); // Active boolean to paint methods
        afterWindows.enable(true);  
        dispose(); // Delete windows
    }//GEN-LAST:event_btnAddFunctionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        afterWindows.enable(true); 
        dispose();
         
    }//GEN-LAST:event_btnExitActionPerformed
    private void loadFunctions(){
        aux = MainApp.methods.getRootFunction();
        while(aux!=null){
            System.out.println(aux.getFuction());
            cmbModel.addElement(aux.getFuction());
            aux= aux.getSig();   
        }cmbFunctions.setModel(cmbModel);
    }
    private Color getColor(String color){ // Methods to get Color through String 
        switch(color){
            case "blue":return Color.blue;
            case "red": return Color.red;
            case "green":return Color.green;
            case "yellow":return Color.yellow;
            case "orange":return Color.orange;
            case "pink":return Color.pink;
            case "magenta":return Color.magenta;
            case "cyan":return Color.cyan;
            
        }return null;
    }
    private String getColorFuctions(String nameFuction){ 
        aux = MainApp.methods.getRootFunction(); // Pointer to Fuctions       
        while(aux!=null){
            if(aux.getFuction().equals(nameFuction)){
                MainApp.methods.setPointerAux(aux);
                return aux.getColor();}
            else{
                aux = aux.getSig();
            }
        }   return "";
    }
    private void checkNameFunction(){ 
        switch(nameFuction){
            case "Start": MainApp.methods.setSpecialFunction(nameFuction); // Change name in methods of SpecialFunction
            case "End": MainApp.methods.setSpecialFunction(nameFuction);
        }
    }
   
    
    public String getNameFuction() {
        return nameFuction;
    }

    public String getColor() {
        return color;
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowsAuxConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowsAuxConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowsAuxConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowsAuxConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new windowsAuxConsult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFunction;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbFunctions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void addMethods(Methods met,JFrame frame) {
        this.afterWindows=frame;
    }
}
